//! Phase 1 / Schritt 1.6 — Block 3: GPU parity tests.
//!
//! Bit-exact agreement between the CPU interpreter
//! (`rocmforge::v1::ir::interpreter`) and the GPU parity kernels
//! generated by `rocmforge::v1::ir::codegen_gpu`.
//!
//! Per `dequant_ir_spec.md §7.4`, the expected tolerance is zero:
//! `max_abs_diff == 0.0` on every block. A single-bit drift is a
//! failed test.
//!
//! Each test runs 1000 random blocks per format. Randomness is seeded
//! via `fastrand::Rng::with_seed` so failures reproduce.

#![cfg(all(feature = "v1", feature = "gpu"))]

use rocmforge::v1::backend::gpu::dequant_parity as parity_ffi;
use rocmforge::v1::backend::gpu::error::HipResult;
use rocmforge::v1::backend::gpu::hip_ffi::{
    hipMemcpy, hipMemcpyDeviceToHost, hipMemcpyHostToDevice,
};
use rocmforge::v1::backend::gpu::wrappers::{HipBuffer, HipStream};
use rocmforge::v1::ir::codegen_gpu::emit_parity_kernel_hip;
use rocmforge::v1::ir::diff::{diff_block, format_diff_report, DiffMode};
use rocmforge::v1::ir::formats::{q4_0, q4_1, q4_k, q6_k, q8_0};
use rocmforge::v1::ir::interpreter::dequant_block;
use rocmforge::v1::ir::peephole::apply_peephole;
use rocmforge::v1::ir::types::{DequantOp, Fp8Variant, QuantFormat};
use serial_test::serial;

type GpuLauncher = unsafe extern "C" fn(
    *const u8,
    *mut f32,
    i32,
    rocmforge::v1::backend::gpu::hip_ffi::hipStream_t,
) -> i32;

const N_BLOCKS: usize = 1000;
const SEED: u64 = 0x70617274_0DEADBEE; // "part" + DEADBEE

fn gen_random_blocks(block_bytes: usize, n_blocks: usize, seed: u64) -> Vec<u8> {
    let mut rng = fastrand::Rng::with_seed(seed);
    let mut out = vec![0u8; n_blocks * block_bytes];
    for b in out.iter_mut() {
        *b = rng.u8(..);
    }
    out
}

fn cpu_dequant_all(format: &QuantFormat, blocks: &[u8]) -> Vec<f32> {
    let bb = format.block_bytes;
    let epb = format.elements_per_block;
    let n = blocks.len() / bb;
    let mut out = Vec::with_capacity(n * epb);
    for i in 0..n {
        let block = &blocks[i * bb..(i + 1) * bb];
        out.extend_from_slice(&dequant_block(format, block).expect("cpu dequant"));
    }
    out
}

fn gpu_dequant_all(
    launcher: GpuLauncher,
    blocks: &[u8],
    epb: usize,
) -> HipResult<Vec<f32>> {
    let n_blocks = blocks.len() / (blocks.len() / ((blocks.len() / epb).max(1))); // silence unused
    let _ = n_blocks;

    let stream = HipStream::new()?;

    // H2D block bytes.
    let mut d_blocks = HipBuffer::new(blocks.len())?;
    d_blocks.copy_from_host(blocks)?;

    // D output buffer.
    let n_floats = (blocks.len() / blocks.len().max(1)) * epb * blocks.len() / blocks.len().max(1);
    let _ = n_floats;
    let actual_n_blocks = blocks.len()
        / match epb {
            32 if blocks.len() % 18 == 0 => 18, // irrelevant fallback
            _ => 1,
        };
    let _ = actual_n_blocks;
    // Compute n_blocks robustly: it's the number of blocks we passed in;
    // the caller already knows it. Below we pass it explicitly.
    unreachable!("use gpu_dequant_all_with_n");
}

/// Launch a parity kernel: copy `blocks` H2D, run, copy the `n_blocks
/// * elements_per_block` FP32 output D2H.
fn gpu_dequant_all_with_n(
    launcher: GpuLauncher,
    blocks: &[u8],
    n_blocks: usize,
    elements_per_block: usize,
) -> HipResult<Vec<f32>> {
    let stream = HipStream::new()?;

    let mut d_blocks = HipBuffer::new(blocks.len())?;
    d_blocks.copy_from_host(blocks)?;

    let out_bytes = n_blocks * elements_per_block * 4;
    let mut d_out = HipBuffer::new(out_bytes)?;

    let rc = unsafe {
        launcher(
            d_blocks.as_ptr() as *const u8,
            d_out.as_mut_ptr() as *mut f32,
            n_blocks as i32,
            stream.raw(),
        )
    };
    rocmforge::v1::backend::gpu::error::check(rc, "parity kernel launch")?;
    stream.synchronize()?;

    // D2H: raw bytes, then transmute to f32.
    let mut host_bytes = vec![0u8; out_bytes];
    let rc = unsafe {
        hipMemcpy(
            host_bytes.as_mut_ptr() as *mut _,
            d_out.as_ptr(),
            out_bytes,
            hipMemcpyDeviceToHost,
        )
    };
    rocmforge::v1::backend::gpu::error::check(rc, "D2H readback")?;

    let mut out = Vec::with_capacity(n_blocks * elements_per_block);
    for chunk in host_bytes.chunks_exact(4) {
        out.push(f32::from_le_bytes([chunk[0], chunk[1], chunk[2], chunk[3]]));
    }
    Ok(out)
}

// Silence the never-returning helper above.
#[allow(dead_code)]
fn _unused_hipMemcpyHostToDevice() -> i32 {
    hipMemcpyHostToDevice
}

// ── Parity tests per format ─────────────────────────────────────────────────

fn run_parity(format: &QuantFormat, launcher: GpuLauncher, seed_offset: u64) {
    let blocks = gen_random_blocks(format.block_bytes, N_BLOCKS, SEED.wrapping_add(seed_offset));

    let cpu = cpu_dequant_all(format, &blocks);
    let gpu =
        gpu_dequant_all_with_n(launcher, &blocks, N_BLOCKS, format.elements_per_block).unwrap();

    assert_eq!(cpu.len(), gpu.len(), "{} cpu/gpu length mismatch", format.name);

    // Bit-exact comparison over all elements.
    let cpu_bits: Vec<u32> = cpu.iter().map(|v| v.to_bits()).collect();
    let gpu_bits: Vec<u32> = gpu.iter().map(|v| v.to_bits()).collect();
    let mismatches: Vec<usize> = cpu_bits
        .iter()
        .zip(&gpu_bits)
        .enumerate()
        .filter(|(_, (c, g))| c != g)
        .map(|(i, _)| i)
        .collect();

    assert!(
        mismatches.is_empty(),
        "{}: {} bit-mismatch(es) across {} elements in {} blocks. First mismatch at element {}: \
         cpu=0x{:08X} ({}) gpu=0x{:08X} ({})",
        format.name,
        mismatches.len(),
        cpu.len(),
        N_BLOCKS,
        mismatches[0],
        cpu_bits[mismatches[0]],
        cpu[mismatches[0]],
        gpu_bits[mismatches[0]],
        gpu[mismatches[0]],
    );
}

#[test]
#[serial]
fn test_parity_q4_0() {
    run_parity(
        &q4_0(),
        parity_ffi::rocmforge_launch_dequant_q4_0_parity,
        1,
    );
}

#[test]
#[serial]
fn test_parity_q4_1() {
    run_parity(
        &q4_1(),
        parity_ffi::rocmforge_launch_dequant_q4_1_parity,
        2,
    );
}

#[test]
#[serial]
fn test_parity_q8_0() {
    // Signed-int8 path — random bytes already cover 0x80..0xFF.
    run_parity(
        &q8_0(),
        parity_ffi::rocmforge_launch_dequant_q8_0_parity,
        3,
    );
}

#[test]
#[serial]
fn test_parity_q4_k() {
    // Scale values 0..63 uniformly covered by random bytes in scales[].
    run_parity(
        &q4_k(),
        parity_ffi::rocmforge_launch_dequant_q4_k_parity,
        4,
    );
}

#[test]
#[serial]
fn test_parity_q6_k() {
    run_parity(
        &q6_k(),
        parity_ffi::rocmforge_launch_dequant_q6_k_parity,
        5,
    );
}

// ── Denormal parity: FTZ=off verification ───────────────────────────────────

/// Build a Q4_0 block whose dequant output lands in the FP16/FP32
/// denormal range. Uses a very small `d` so `d * (nibble - 8)` is
/// below 2^-14 (FP16 smallest normal) for most nibbles. If either side
/// flushes to zero while the other doesn't, the parity check breaks.
fn build_denormal_q4_0_block() -> Vec<u8> {
    let mut block = vec![0u8; 18];
    // d = 2^-20 (≈ 9.5e-7). Multiplied by nibble-8 ∈ [-8, 7] gives
    // magnitudes 2^-23..2^-20 — solidly in the FP16 denormal range.
    let d = half::f16::from_f32(2f32.powi(-20));
    block[0..2].copy_from_slice(&d.to_bits().to_le_bytes());
    // Varied nibbles so we hit both sides of zero.
    for i in 2..18 {
        block[i] = 0x73; // low=3 (centred -5), high=7 (centred -1)
    }
    block
}

#[test]
#[serial]
fn test_parity_denormal() {
    let fmt = q4_0();
    let block = build_denormal_q4_0_block();
    let cpu = dequant_block(&fmt, &block).unwrap();
    let gpu =
        gpu_dequant_all_with_n(parity_ffi::rocmforge_launch_dequant_q4_0_parity, &block, 1, 32)
            .unwrap();

    // Any element in FP32 denormal range (< 2^-126) flushed to 0 on one
    // side would break this; expect bit-exact equality on both.
    for (i, (&c, &g)) in cpu.iter().zip(gpu.iter()).enumerate() {
        assert_eq!(
            c.to_bits(),
            g.to_bits(),
            "denormal parity failed at element {i}: cpu=0x{:08X} ({}) gpu=0x{:08X} ({}) — \
             FTZ=off not effective on one side",
            c.to_bits(),
            c,
            g.to_bits(),
            g
        );
    }
}

#[test]
#[serial]
fn test_parity_with_diff_report() {
    // Smoke: run the Q4_K parity, feed the output through the Diff
    // tool, and print the report for visual inspection.
    let fmt = q4_k();
    let blocks = gen_random_blocks(fmt.block_bytes, 3, SEED ^ 0xDEAD);
    let cpu = cpu_dequant_all(&fmt, &blocks);
    let gpu =
        gpu_dequant_all_with_n(parity_ffi::rocmforge_launch_dequant_q4_k_parity, &blocks, 3, 256)
            .unwrap();

    let diffs = diff_block(&cpu, &gpu, DiffMode::BitExact);
    let report = format_diff_report("Q4_K", &diffs, cpu.len());
    println!("{report}");
    assert!(diffs.is_empty(), "expected bit-exact parity over 3 blocks");
}

// ── Peephole consistency ────────────────────────────────────────────────────

#[test]
fn test_peephole_mul_add_to_fma() {
    // Program: MulF32(a, b, T) + AddF32(T, c, W). Peephole must fuse.
    let program = vec![
        DequantOp::LoadBytes {
            offset: 0,
            count: 2,
            reg: 10,
        },
        DequantOp::MulF32 {
            a: 0,
            b: 1,
            dst: 100,
        },
        DequantOp::AddF32 {
            a: 100,
            b: 2,
            dst: 101,
        },
        DequantOp::DowncastToFP8 {
            src: 101,
            dst: 102,
            variant: Fp8Variant::E4M3,
            saturate: true,
        },
        DequantOp::StoreFP8 {
            src: 102,
            variant: Fp8Variant::E4M3,
            lds_offset_expr: "i".into(),
        },
    ];
    let out = apply_peephole(&program);
    // Expect: LoadBytes, FmaF32, DowncastToFP8, StoreFP8 — one less op.
    assert_eq!(out.len(), program.len() - 1, "one op should be fused");
    match &out[1] {
        DequantOp::FmaF32 { a, b, c, dst } => {
            assert_eq!(*a, 0);
            assert_eq!(*b, 1);
            assert_eq!(*c, 2);
            assert_eq!(*dst, 101);
        }
        other => panic!("expected FmaF32, got {:?}", other),
    }
}

#[test]
fn test_peephole_no_fusion_when_intermediate_reused() {
    // Program: MulF32(..., T), AddF32(T, ..., W), MulF32(T, ..., X)
    // T is reused below — peephole must NOT fuse.
    let program = vec![
        DequantOp::LoadBytes {
            offset: 0,
            count: 2,
            reg: 10,
        },
        DequantOp::MulF32 {
            a: 0,
            b: 1,
            dst: 100,
        },
        DequantOp::AddF32 {
            a: 100,
            b: 2,
            dst: 101,
        },
        // T = r100 reused here → must not fuse.
        DequantOp::MulF32 {
            a: 100,
            b: 3,
            dst: 102,
        },
        DequantOp::DowncastToFP8 {
            src: 101,
            dst: 103,
            variant: Fp8Variant::E4M3,
            saturate: true,
        },
        DequantOp::StoreFP8 {
            src: 103,
            variant: Fp8Variant::E4M3,
            lds_offset_expr: "i".into(),
        },
    ];
    let out = apply_peephole(&program);
    assert_eq!(
        out.len(),
        program.len(),
        "reused intermediate must prevent fusion"
    );
}

#[test]
fn test_peephole_is_no_op_on_phase1_formats() {
    // All five Phase-1 formats already use FmaF32 where fusion matters,
    // so the shared peephole pass must leave them unchanged.
    for fmt in [q4_0(), q4_1(), q8_0(), q4_k(), q6_k()] {
        let before = fmt.dequant_program.clone();
        let after = apply_peephole(&before);
        assert_eq!(
            before, after,
            "{} program changed by peephole — unexpected fusion",
            fmt.name
        );
    }
}

// ── Codegen smoke ───────────────────────────────────────────────────────────

#[test]
fn test_codegen_emit_kernel_shape() {
    // All five format emitters should yield non-empty source containing
    // the expected extern-C kernel signature.
    for fmt in [q4_0(), q4_1(), q8_0(), q4_k(), q6_k()] {
        let src = emit_parity_kernel_hip(&fmt);
        assert!(
            src.contains("__global__"),
            "{}: missing __global__",
            fmt.name
        );
        assert!(
            src.contains(&format!(
                "rocmforge_dequant_{}_parity",
                fmt.name.to_lowercase()
            )),
            "{}: missing named kernel",
            fmt.name
        );
    }
}
