//! GPU codegen — emits HIP C++ source for a Level-3 (FP32 output) parity
//! test kernel per Phase-1 QuantFormat.
//!
//! Scope (Phase 1). The full emitter described in `dequant_ir_spec.md §6`
//! needs linear-scan register allocation, FP8 pair-packing, and hipRTC
//! runtime compilation. Phase 1 only needs a **standalone test kernel**
//! that consumes one block and writes `elements_per_block` FP32 values
//! — enough to verify bit-exact parity with the CPU interpreter
//! (`super::interpreter`).
//!
//! Output format. Each `emit_parity_kernel_hip` produces a complete
//! `extern "C" __global__` HIP kernel. Source is deterministic — same
//! input always yields byte-identical output — so tests can assert
//! textual stability and the build step can write it to disk.
//!
//! Instruction mapping follows §6.2. We rely on `hipcc` to lower C
//! operations to the target instructions rather than emitting intrinsics
//! directly:
//!
//!   * `float(uint8_t)` → `v_cvt_f32_ubyte0`
//!   * `float(int8_t)`  → `v_cvt_f32_i32`
//!   * `a * b`          → `v_mul_f32`
//!   * `fmaf(a, b, c)`  → `v_fma_f32` (single-rounding RNE)
//!   * `a - b`          → `v_sub_f32`
//!   * `(x >> 16) & 0xFFFF` of an FP16-raw-u16 → handled via __half
//!
//! Single-rounding FMA matches the CPU interpreter's
//! `f32::mul_add` (§7.4 Rule 1).
//!
//! The kernel prolog explicitly sets MODE.FP_DENORM = 0xF (§7.4 Rule 4)
//! so FP32/FP16 denormals are preserved on gfx1201, matching the
//! CPU-side MXCSR = `FTZ=0, DAZ=0`.

use super::types::QuantFormat;

/// Emit a parity-test kernel for any of the five Phase-1 formats.
/// Returns a ready-to-compile HIP C++ source string.
pub fn emit_parity_kernel_hip(format: &QuantFormat) -> String {
    match format.id {
        2 => emit_q4_0_parity(),
        3 => emit_q4_1_parity(),
        8 => emit_q8_0_parity(),
        12 => emit_q4_k_parity(),
        14 => emit_q6_k_parity(),
        other => format!("// unsupported format id {other}\n"),
    }
}

/// Emit a single compilation unit containing all five parity kernels +
/// a shared launcher. Used by `build.rs` to produce the static library.
pub fn emit_all_parity_kernels() -> String {
    let mut s = String::new();
    s.push_str(FILE_HEADER);
    s.push_str(&emit_q4_0_parity());
    s.push_str(&emit_q4_1_parity());
    s.push_str(&emit_q8_0_parity());
    s.push_str(&emit_q4_k_parity());
    s.push_str(&emit_q6_k_parity());
    s.push_str(&emit_launchers());
    s
}

const FILE_HEADER: &str = r#"// Auto-generated by src_v1/ir/codegen_gpu.rs — do not edit by hand.
// Level-3 FP32 parity kernels for the five Phase-1 QuantFormats.

#include <hip/hip_runtime.h>
#include <hip/hip_fp16.h>
#include <stdint.h>

// Force MODE.FP_DENORM = 0xF so FP32/FP16 denormals are preserved
// (dequant_ir_spec.md §7.4 Rule 4, §10.5). This matches the CPU side's
// MXCSR FTZ=off / DAZ=off.
__device__ __forceinline__ void rf_v1_set_ieee_denormal_mode() {
    asm volatile("s_setreg_imm32_b32 hwreg(HW_REG_MODE, 4, 4), 0xF");
}

// FP16 bit-pattern → FP32. hipcc lowers __half_raw cast to v_cvt_f32_f16.
__device__ __forceinline__ float fp16_to_fp32(uint16_t raw) {
    __half_raw hr;
    hr.x = raw;
    return __half2float(__half(hr));
}

// Load a little-endian u16 from two bytes at `p + offset`.
__device__ __forceinline__ uint16_t load_u16_le(const uint8_t* p, int offset) {
    return (uint16_t)p[offset] | ((uint16_t)p[offset + 1] << 8);
}

"#;

// --- Q4_0 ------------------------------------------------------------

fn emit_q4_0_parity() -> String {
    r#"// Q4_0: 18 B / 32 elements. value = d * (nibble - 8).
extern "C" __global__
void rocmforge_dequant_q4_0_parity(
    const uint8_t* __restrict__ blocks,
    float* __restrict__ output,
    int n_blocks)
{
    rf_v1_set_ieee_denormal_mode();
    int block_id = blockIdx.x;
    int elem     = threadIdx.x;
    if (block_id >= n_blocks || elem >= 32) return;

    const uint8_t* block = blocks + block_id * 18;
    float d = fp16_to_fp32(load_u16_le(block, 0));

    int byte_idx = elem % 16;
    bool high    = elem >= 16;
    uint8_t b    = block[2 + byte_idx];
    int nibble   = high ? ((b >> 4) & 0x0F) : (b & 0x0F);

    float q_fp       = float(nibble);
    float q_centered = q_fp - 8.0f;
    float val        = d * q_centered;

    output[block_id * 32 + elem] = val;
}

"#.to_string()
}

// --- Q4_1 ------------------------------------------------------------

fn emit_q4_1_parity() -> String {
    r#"// Q4_1: 20 B / 32 elements. value = fmaf(nibble, d, m).
extern "C" __global__
void rocmforge_dequant_q4_1_parity(
    const uint8_t* __restrict__ blocks,
    float* __restrict__ output,
    int n_blocks)
{
    rf_v1_set_ieee_denormal_mode();
    int block_id = blockIdx.x;
    int elem     = threadIdx.x;
    if (block_id >= n_blocks || elem >= 32) return;

    const uint8_t* block = blocks + block_id * 20;
    float d = fp16_to_fp32(load_u16_le(block, 0));
    float m = fp16_to_fp32(load_u16_le(block, 2));

    int byte_idx = elem % 16;
    bool high    = elem >= 16;
    uint8_t b    = block[4 + byte_idx];
    int nibble   = high ? ((b >> 4) & 0x0F) : (b & 0x0F);

    // Single-rounding FMA — matches CPU f32::mul_add (§7.4 Rule 1).
    float val = fmaf(float(nibble), d, m);

    output[block_id * 32 + elem] = val;
}

"#.to_string()
}

// --- Q8_0 ------------------------------------------------------------

fn emit_q8_0_parity() -> String {
    r#"// Q8_0: 34 B / 32 elements. qs[i] is SIGNED int8. value = d * int8(qs).
extern "C" __global__
void rocmforge_dequant_q8_0_parity(
    const uint8_t* __restrict__ blocks,
    float* __restrict__ output,
    int n_blocks)
{
    rf_v1_set_ieee_denormal_mode();
    int block_id = blockIdx.x;
    int elem     = threadIdx.x;
    if (block_id >= n_blocks || elem >= 32) return;

    const uint8_t* block = blocks + block_id * 34;
    float d   = fp16_to_fp32(load_u16_le(block, 0));
    int8_t q8 = (int8_t)block[2 + elem];           // signed reinterpret
    float val = d * float(int(q8));

    output[block_id * 32 + elem] = val;
}

"#.to_string()
}

// --- Q4_K ------------------------------------------------------------

fn emit_q4_k_parity() -> String {
    r#"// Q4_K: 144 B / 256 elements. 8 sub-blocks × 32 elements, pair-interleaved
// nibble layout (k=0..4 pair (2k, 2k+1) consumes qs[k*32..k*32+32]).
// Scale/min: 6-bit packed via get_scale_min_k4 — raw 0..63, NO /64.
// value = fmaf(nibble_fp, d_eff, -dmin_eff).
extern "C" __global__
void rocmforge_dequant_q4_k_parity(
    const uint8_t* __restrict__ blocks,
    float* __restrict__ output,
    int n_blocks)
{
    rf_v1_set_ieee_denormal_mode();
    int block_id = blockIdx.x;
    int elem     = threadIdx.x;    // 0..256
    if (block_id >= n_blocks || elem >= 256) return;

    const uint8_t* block  = blocks + block_id * 144;
    float d               = fp16_to_fp32(load_u16_le(block, 0));
    float dmin            = fp16_to_fp32(load_u16_le(block, 2));
    const uint8_t* scales = block + 4;
    const uint8_t* qs     = block + 16;

    // Sub-block index + pair decomposition (§3.6, §6.4).
    int sub_j     = elem / 32;
    int elem_in_sb = elem % 32;
    int pair_idx  = sub_j / 2;
    int pair_base = pair_idx * 32;
    int byte_idx  = pair_base + elem_in_sb;
    bool high     = (sub_j & 1) == 1;
    uint8_t b     = qs[byte_idx];
    int nibble    = high ? ((b >> 4) & 0x0F) : (b & 0x0F);

    // get_scale_min_k4 — raw 6-bit ints 0..63.
    int sc_int, mi_int;
    if (sub_j < 4) {
        sc_int = scales[sub_j]     & 0x3F;
        mi_int = scales[sub_j + 4] & 0x3F;
    } else {
        sc_int = (scales[sub_j + 4] & 0x0F) | ((scales[sub_j - 4] >> 6) << 4);
        mi_int = (scales[sub_j + 4] >> 4)   | ((scales[sub_j]     >> 6) << 4);
    }

    float sc     = float(sc_int);
    float mi     = float(mi_int);
    float d_eff  = d    * sc;
    float dm_eff = dmin * mi;

    // Single-rounding FMA with negated c-operand (matches CPU's mul_add(d_eff, -dm_eff)).
    float val = fmaf(float(nibble), d_eff, -dm_eff);

    output[block_id * 256 + elem] = val;
}

"#.to_string()
}

// --- Q6_K ------------------------------------------------------------
//
// Follows llama.cpp `dequantize_row_q6_K` (not spec §3.7's simple qh
// layout — see interpreter.rs discrepancy note). Each block writes 256
// values in two 128-element chunks, each chunk processed as 32
// iterations of l writing 4 positions (l, l+32, l+64, l+96).
fn emit_q6_k_parity() -> String {
    r#"// Q6_K: 210 B / 256 elements. d at offset 208 (NOT 0).
// ql[128] @ 0, qh[64] @ 128, i8 scales[16] @ 192, d[fp16] @ 208.
// value = d * sc[is] * (q6 - 32), with q6 = ql_nibble | (qh_2bits << 4).
extern "C" __global__
void rocmforge_dequant_q6_k_parity(
    const uint8_t* __restrict__ blocks,
    float* __restrict__ output,
    int n_blocks)
{
    rf_v1_set_ieee_denormal_mode();
    int block_id = blockIdx.x;
    int elem     = threadIdx.x;    // 0..256
    if (block_id >= n_blocks || elem >= 256) return;

    const uint8_t* block = blocks + block_id * 210;

    // Chunk of 128: elem ∈ [0,128) uses ql[0..128]+qh[0..32]+sc[0..8];
    //               elem ∈ [128,256) uses ql[64..192 of ql]+qh[32..64]+sc[8..16].
    int chunk       = elem / 128;           // 0 or 1
    int within_chunk = elem % 128;          // 0..128
    int group       = within_chunk / 32;    // 0,1,2,3 → one of q1,q2,q3,q4
    int l           = within_chunk % 32;    // inner index

    int ql_base = chunk * 64;   // +0 or +64 into ql[128]
    int qh_base = chunk * 32;   // +0 or +32 into qh[64]
    int sc_base = chunk * 8;    // +0 or +8 into scales[16]

    const uint8_t* ql = block + 0   + ql_base;
    const uint8_t* qh = block + 128 + qh_base;
    // Signed int8 scales.
    const int8_t* sc  = (const int8_t*)(block + 192 + sc_base);
    float d = fp16_to_fp32(load_u16_le(block, 208));

    int is = l / 16;

    // Map group 0..3 → (ql_byte_idx, ql_high, qh_shift, sc_idx, out_offset)
    int ql_byte_idx, sc_idx;
    bool ql_high;
    int qh_shift;
    if (group == 0) {
        ql_byte_idx = l;      ql_high = false; qh_shift = 0; sc_idx = is + 0;
    } else if (group == 1) {
        ql_byte_idx = l + 32; ql_high = false; qh_shift = 2; sc_idx = is + 2;
    } else if (group == 2) {
        ql_byte_idx = l;      ql_high = true;  qh_shift = 4; sc_idx = is + 4;
    } else /* 3 */ {
        ql_byte_idx = l + 32; ql_high = true;  qh_shift = 6; sc_idx = is + 6;
    }

    uint8_t ql_byte = ql[ql_byte_idx];
    int ql_nibble   = ql_high ? ((ql_byte >> 4) & 0x0F) : (ql_byte & 0x0F);
    int qh_2bits    = (qh[l] >> qh_shift) & 0x03;
    int q6_combined = ql_nibble | (qh_2bits << 4);
    int q6_signed   = (int)((int8_t)q6_combined) - 32;

    float sc_fp = float(int(sc[sc_idx]));
    float val   = d * sc_fp * float(q6_signed);

    output[block_id * 256 + elem] = val;
}

"#.to_string()
}

// --- Launcher helpers (C) --------------------------------------------

fn emit_launchers() -> String {
    r#"// Thin C launchers so the Rust side can invoke the kernels without
// parsing HIP grid/block types.

extern "C" hipError_t rocmforge_launch_dequant_q4_0_parity(
    const uint8_t* d_blocks, float* d_output, int n_blocks, hipStream_t stream)
{
    dim3 grid(n_blocks), block(32);
    rocmforge_dequant_q4_0_parity<<<grid, block, 0, stream>>>(d_blocks, d_output, n_blocks);
    return hipGetLastError();
}

extern "C" hipError_t rocmforge_launch_dequant_q4_1_parity(
    const uint8_t* d_blocks, float* d_output, int n_blocks, hipStream_t stream)
{
    dim3 grid(n_blocks), block(32);
    rocmforge_dequant_q4_1_parity<<<grid, block, 0, stream>>>(d_blocks, d_output, n_blocks);
    return hipGetLastError();
}

extern "C" hipError_t rocmforge_launch_dequant_q8_0_parity(
    const uint8_t* d_blocks, float* d_output, int n_blocks, hipStream_t stream)
{
    dim3 grid(n_blocks), block(32);
    rocmforge_dequant_q8_0_parity<<<grid, block, 0, stream>>>(d_blocks, d_output, n_blocks);
    return hipGetLastError();
}

extern "C" hipError_t rocmforge_launch_dequant_q4_k_parity(
    const uint8_t* d_blocks, float* d_output, int n_blocks, hipStream_t stream)
{
    dim3 grid(n_blocks), block(256);
    rocmforge_dequant_q4_k_parity<<<grid, block, 0, stream>>>(d_blocks, d_output, n_blocks);
    return hipGetLastError();
}

extern "C" hipError_t rocmforge_launch_dequant_q6_k_parity(
    const uint8_t* d_blocks, float* d_output, int n_blocks, hipStream_t stream)
{
    dim3 grid(n_blocks), block(256);
    rocmforge_dequant_q6_k_parity<<<grid, block, 0, stream>>>(d_blocks, d_output, n_blocks);
    return hipGetLastError();
}
"#.to_string()
}
