//! GPU codegen — emits HIP C++ source for a Level-3 (FP32 output) parity
//! test kernel per Phase-1 QuantFormat.
//!
//! Scope (Phase 1). The full emitter described in `dequant_ir_spec.md §6`
//! needs linear-scan register allocation, FP8 pair-packing, and hipRTC
//! runtime compilation. Phase 1 only needs a **standalone test kernel**
//! that consumes one block and writes `elements_per_block` FP32 values
//! — enough to verify bit-exact parity with the CPU interpreter
//! (`super::interpreter`).
//!
//! Output format. Each `emit_parity_kernel_hip` produces a complete
//! `extern "C" __global__` HIP kernel. Source is deterministic — same
//! input always yields byte-identical output — so tests can assert
//! textual stability and the build step can write it to disk.
//!
//! Instruction mapping follows §6.2. We rely on `hipcc` to lower C
//! operations to the target instructions rather than emitting intrinsics
//! directly:
//!
//!   * `float(uint8_t)` → `v_cvt_f32_ubyte0`
//!   * `float(int8_t)`  → `v_cvt_f32_i32`
//!   * `a * b`          → `v_mul_f32`
//!   * `fmaf(a, b, c)`  → `v_fma_f32` (single-rounding RNE)
//!   * `a - b`          → `v_sub_f32`
//!   * `(x >> 16) & 0xFFFF` of an FP16-raw-u16 → handled via __half
//!
//! Single-rounding FMA matches the CPU interpreter's
//! `f32::mul_add` (§7.4 Rule 1).
//!
//! The kernel prolog explicitly sets MODE.FP_DENORM = 0xF (§7.4 Rule 4)
//! so FP32/FP16 denormals are preserved on gfx1201, matching the
//! CPU-side MXCSR = `FTZ=0, DAZ=0`.

use super::types::QuantFormat;

/// Precision level targeted by a generated kernel. Maps to the WMMA
/// intrinsic and LDS element size (`dequant_ir_spec.md §4`, §5.2).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Precision {
    /// Level 0 — FP8 E4M3 weights/inputs, FP32 accumulator. Default
    /// for production (smaller LDS footprint, higher occupancy).
    Fp8,
    /// Level 1 — FP16 weights/inputs, FP32 accumulator. Fallback for
    /// SNR-sensitive layers; matches v0.x WMMA precision exactly.
    Fp16,
}

/// Emit a parity-test kernel for any of the five Phase-1 formats.
/// Returns a ready-to-compile HIP C++ source string.
pub fn emit_parity_kernel_hip(format: &QuantFormat) -> String {
    match format.id {
        2 => emit_q4_0_parity(),
        3 => emit_q4_1_parity(),
        8 => emit_q8_0_parity(),
        12 => emit_q4_k_parity(),
        14 => emit_q6_k_parity(),
        other => format!("// unsupported format id {other}\n"),
    }
}

/// Emit a single compilation unit containing all five parity kernels +
/// a shared launcher. Used by `build.rs` to produce the static library.
pub fn emit_all_parity_kernels() -> String {
    let mut s = String::new();
    s.push_str(FILE_HEADER);
    s.push_str(&emit_q4_0_parity());
    s.push_str(&emit_q4_1_parity());
    s.push_str(&emit_q8_0_parity());
    s.push_str(&emit_q4_k_parity());
    s.push_str(&emit_q6_k_parity());
    s.push_str(&emit_launchers());
    s
}

const FILE_HEADER: &str = r#"// Auto-generated by src_v1/ir/codegen_gpu.rs — do not edit by hand.
// Level-3 FP32 parity kernels for the five Phase-1 QuantFormats.

#include <hip/hip_runtime.h>
#include <hip/hip_fp16.h>
#include <stdint.h>

// Force MODE.FP_DENORM = 0xF so FP32/FP16 denormals are preserved
// (dequant_ir_spec.md §7.4 Rule 4, §10.5). This matches the CPU side's
// MXCSR FTZ=off / DAZ=off.
__device__ __forceinline__ void rf_v1_set_ieee_denormal_mode() {
    asm volatile("s_setreg_imm32_b32 hwreg(HW_REG_MODE, 4, 4), 0xF");
}

// FP16 bit-pattern → FP32. hipcc lowers __half_raw cast to v_cvt_f32_f16.
__device__ __forceinline__ float fp16_to_fp32(uint16_t raw) {
    __half_raw hr;
    hr.x = raw;
    return __half2float(__half(hr));
}

// Load a little-endian u16 from two bytes at `p + offset`.
__device__ __forceinline__ uint16_t load_u16_le(const uint8_t* p, int offset) {
    return (uint16_t)p[offset] | ((uint16_t)p[offset + 1] << 8);
}

"#;

// --- Q4_0 ------------------------------------------------------------

fn emit_q4_0_parity() -> String {
    r#"// Q4_0: 18 B / 32 elements. value = d * (nibble - 8).
extern "C" __global__
void rocmforge_dequant_q4_0_parity(
    const uint8_t* __restrict__ blocks,
    float* __restrict__ output,
    int n_blocks)
{
    rf_v1_set_ieee_denormal_mode();
    int block_id = blockIdx.x;
    int elem     = threadIdx.x;
    if (block_id >= n_blocks || elem >= 32) return;

    const uint8_t* block = blocks + block_id * 18;
    float d = fp16_to_fp32(load_u16_le(block, 0));

    int byte_idx = elem % 16;
    bool high    = elem >= 16;
    uint8_t b    = block[2 + byte_idx];
    int nibble   = high ? ((b >> 4) & 0x0F) : (b & 0x0F);

    float q_fp       = float(nibble);
    float q_centered = q_fp - 8.0f;
    float val        = d * q_centered;

    output[block_id * 32 + elem] = val;
}

"#.to_string()
}

// --- Q4_1 ------------------------------------------------------------

fn emit_q4_1_parity() -> String {
    r#"// Q4_1: 20 B / 32 elements. value = fmaf(nibble, d, m).
extern "C" __global__
void rocmforge_dequant_q4_1_parity(
    const uint8_t* __restrict__ blocks,
    float* __restrict__ output,
    int n_blocks)
{
    rf_v1_set_ieee_denormal_mode();
    int block_id = blockIdx.x;
    int elem     = threadIdx.x;
    if (block_id >= n_blocks || elem >= 32) return;

    const uint8_t* block = blocks + block_id * 20;
    float d = fp16_to_fp32(load_u16_le(block, 0));
    float m = fp16_to_fp32(load_u16_le(block, 2));

    int byte_idx = elem % 16;
    bool high    = elem >= 16;
    uint8_t b    = block[4 + byte_idx];
    int nibble   = high ? ((b >> 4) & 0x0F) : (b & 0x0F);

    // Single-rounding FMA — matches CPU f32::mul_add (§7.4 Rule 1).
    float val = fmaf(float(nibble), d, m);

    output[block_id * 32 + elem] = val;
}

"#.to_string()
}

// --- Q8_0 ------------------------------------------------------------

fn emit_q8_0_parity() -> String {
    r#"// Q8_0: 34 B / 32 elements. qs[i] is SIGNED int8. value = d * int8(qs).
extern "C" __global__
void rocmforge_dequant_q8_0_parity(
    const uint8_t* __restrict__ blocks,
    float* __restrict__ output,
    int n_blocks)
{
    rf_v1_set_ieee_denormal_mode();
    int block_id = blockIdx.x;
    int elem     = threadIdx.x;
    if (block_id >= n_blocks || elem >= 32) return;

    const uint8_t* block = blocks + block_id * 34;
    float d   = fp16_to_fp32(load_u16_le(block, 0));
    int8_t q8 = (int8_t)block[2 + elem];           // signed reinterpret
    float val = d * float(int(q8));

    output[block_id * 32 + elem] = val;
}

"#.to_string()
}

// --- Q4_K ------------------------------------------------------------

fn emit_q4_k_parity() -> String {
    r#"// Q4_K: 144 B / 256 elements. 8 sub-blocks × 32 elements, pair-interleaved
// nibble layout (k=0..4 pair (2k, 2k+1) consumes qs[k*32..k*32+32]).
// Scale/min: 6-bit packed via get_scale_min_k4 — raw 0..63, NO /64.
// value = fmaf(nibble_fp, d_eff, -dmin_eff).
extern "C" __global__
void rocmforge_dequant_q4_k_parity(
    const uint8_t* __restrict__ blocks,
    float* __restrict__ output,
    int n_blocks)
{
    rf_v1_set_ieee_denormal_mode();
    int block_id = blockIdx.x;
    int elem     = threadIdx.x;    // 0..256
    if (block_id >= n_blocks || elem >= 256) return;

    const uint8_t* block  = blocks + block_id * 144;
    float d               = fp16_to_fp32(load_u16_le(block, 0));
    float dmin            = fp16_to_fp32(load_u16_le(block, 2));
    const uint8_t* scales = block + 4;
    const uint8_t* qs     = block + 16;

    // Sub-block index + pair decomposition (§3.6, §6.4).
    int sub_j     = elem / 32;
    int elem_in_sb = elem % 32;
    int pair_idx  = sub_j / 2;
    int pair_base = pair_idx * 32;
    int byte_idx  = pair_base + elem_in_sb;
    bool high     = (sub_j & 1) == 1;
    uint8_t b     = qs[byte_idx];
    int nibble    = high ? ((b >> 4) & 0x0F) : (b & 0x0F);

    // get_scale_min_k4 — raw 6-bit ints 0..63.
    int sc_int, mi_int;
    if (sub_j < 4) {
        sc_int = scales[sub_j]     & 0x3F;
        mi_int = scales[sub_j + 4] & 0x3F;
    } else {
        sc_int = (scales[sub_j + 4] & 0x0F) | ((scales[sub_j - 4] >> 6) << 4);
        mi_int = (scales[sub_j + 4] >> 4)   | ((scales[sub_j]     >> 6) << 4);
    }

    float sc     = float(sc_int);
    float mi     = float(mi_int);
    float d_eff  = d    * sc;
    float dm_eff = dmin * mi;

    // Single-rounding FMA with negated c-operand (matches CPU's mul_add(d_eff, -dm_eff)).
    float val = fmaf(float(nibble), d_eff, -dm_eff);

    output[block_id * 256 + elem] = val;
}

"#.to_string()
}

// --- Q6_K ------------------------------------------------------------
//
// Follows llama.cpp `dequantize_row_q6_K` (not spec §3.7's simple qh
// layout — see interpreter.rs discrepancy note). Each block writes 256
// values in two 128-element chunks, each chunk processed as 32
// iterations of l writing 4 positions (l, l+32, l+64, l+96).
fn emit_q6_k_parity() -> String {
    r#"// Q6_K: 210 B / 256 elements. d at offset 208 (NOT 0).
// ql[128] @ 0, qh[64] @ 128, i8 scales[16] @ 192, d[fp16] @ 208.
// value = d * sc[is] * (q6 - 32), with q6 = ql_nibble | (qh_2bits << 4).
extern "C" __global__
void rocmforge_dequant_q6_k_parity(
    const uint8_t* __restrict__ blocks,
    float* __restrict__ output,
    int n_blocks)
{
    rf_v1_set_ieee_denormal_mode();
    int block_id = blockIdx.x;
    int elem     = threadIdx.x;    // 0..256
    if (block_id >= n_blocks || elem >= 256) return;

    const uint8_t* block = blocks + block_id * 210;

    // Chunk of 128: elem ∈ [0,128) uses ql[0..128]+qh[0..32]+sc[0..8];
    //               elem ∈ [128,256) uses ql[64..192 of ql]+qh[32..64]+sc[8..16].
    int chunk       = elem / 128;           // 0 or 1
    int within_chunk = elem % 128;          // 0..128
    int group       = within_chunk / 32;    // 0,1,2,3 → one of q1,q2,q3,q4
    int l           = within_chunk % 32;    // inner index

    int ql_base = chunk * 64;   // +0 or +64 into ql[128]
    int qh_base = chunk * 32;   // +0 or +32 into qh[64]
    int sc_base = chunk * 8;    // +0 or +8 into scales[16]

    const uint8_t* ql = block + 0   + ql_base;
    const uint8_t* qh = block + 128 + qh_base;
    // Signed int8 scales.
    const int8_t* sc  = (const int8_t*)(block + 192 + sc_base);
    float d = fp16_to_fp32(load_u16_le(block, 208));

    int is = l / 16;

    // Map group 0..3 → (ql_byte_idx, ql_high, qh_shift, sc_idx, out_offset)
    int ql_byte_idx, sc_idx;
    bool ql_high;
    int qh_shift;
    if (group == 0) {
        ql_byte_idx = l;      ql_high = false; qh_shift = 0; sc_idx = is + 0;
    } else if (group == 1) {
        ql_byte_idx = l + 32; ql_high = false; qh_shift = 2; sc_idx = is + 2;
    } else if (group == 2) {
        ql_byte_idx = l;      ql_high = true;  qh_shift = 4; sc_idx = is + 4;
    } else /* 3 */ {
        ql_byte_idx = l + 32; ql_high = true;  qh_shift = 6; sc_idx = is + 6;
    }

    uint8_t ql_byte = ql[ql_byte_idx];
    int ql_nibble   = ql_high ? ((ql_byte >> 4) & 0x0F) : (ql_byte & 0x0F);
    int qh_2bits    = (qh[l] >> qh_shift) & 0x03;
    int q6_combined = ql_nibble | (qh_2bits << 4);
    int q6_signed   = (int)((int8_t)q6_combined) - 32;

    float sc_fp = float(int(sc[sc_idx]));
    float val   = d * sc_fp * float(q6_signed);

    output[block_id * 256 + elem] = val;
}

"#.to_string()
}

// --- Launcher helpers (C) --------------------------------------------

fn emit_launchers() -> String {
    r#"// Thin C launchers so the Rust side can invoke the kernels without
// parsing HIP grid/block types.

extern "C" hipError_t rocmforge_launch_dequant_q4_0_parity(
    const uint8_t* d_blocks, float* d_output, int n_blocks, hipStream_t stream)
{
    dim3 grid(n_blocks), block(32);
    rocmforge_dequant_q4_0_parity<<<grid, block, 0, stream>>>(d_blocks, d_output, n_blocks);
    return hipGetLastError();
}

extern "C" hipError_t rocmforge_launch_dequant_q4_1_parity(
    const uint8_t* d_blocks, float* d_output, int n_blocks, hipStream_t stream)
{
    dim3 grid(n_blocks), block(32);
    rocmforge_dequant_q4_1_parity<<<grid, block, 0, stream>>>(d_blocks, d_output, n_blocks);
    return hipGetLastError();
}

extern "C" hipError_t rocmforge_launch_dequant_q8_0_parity(
    const uint8_t* d_blocks, float* d_output, int n_blocks, hipStream_t stream)
{
    dim3 grid(n_blocks), block(32);
    rocmforge_dequant_q8_0_parity<<<grid, block, 0, stream>>>(d_blocks, d_output, n_blocks);
    return hipGetLastError();
}

extern "C" hipError_t rocmforge_launch_dequant_q4_k_parity(
    const uint8_t* d_blocks, float* d_output, int n_blocks, hipStream_t stream)
{
    dim3 grid(n_blocks), block(256);
    rocmforge_dequant_q4_k_parity<<<grid, block, 0, stream>>>(d_blocks, d_output, n_blocks);
    return hipGetLastError();
}

extern "C" hipError_t rocmforge_launch_dequant_q6_k_parity(
    const uint8_t* d_blocks, float* d_output, int n_blocks, hipStream_t stream)
{
    dim3 grid(n_blocks), block(256);
    rocmforge_dequant_q6_k_parity<<<grid, block, 0, stream>>>(d_blocks, d_output, n_blocks);
    return hipGetLastError();
}
"#.to_string()
}

// ─── WMMA-GEMM kernels (Phase 1 Schritt 1.7) ──────────────────────────────
//
// Phase 1 strategy: textual v0.x-kernel template with the dequant block
// kept inline as a hardcoded C++ snippet per format. A "real" IR-driven
// element-loop generator is a Phase-2 optimisation per the user's
// decision at the Schritt-1.7 scope-clarification stop.
//
// Layout inherited 1:1 from the v0.x handwritten kernels
// (`hip_kernels/wmma/wmma_gemm_q4_0.hip`) — tile sizes, wave geometry,
// WMMA A/B fragment offsets are known-good on gfx1201 and must not be
// reinvented.

/// Emit a complete WMMA GEMM kernel file (one .hip compilation unit,
/// including launcher) for the given `(format, precision)` pair. Only
/// combinations that have a Phase-1 emitter return non-empty output.
pub fn emit_wmma_gemm_kernel(format: &QuantFormat, precision: Precision) -> String {
    match (format.id, precision) {
        (2, Precision::Fp16) => emit_q4_0_wmma_fp16(),
        (8, Precision::Fp16) => emit_q8_0_wmma_fp16(),
        (12, Precision::Fp16) => emit_q4_k_wmma_fp16(),
        (14, Precision::Fp16) => emit_q6_k_wmma_fp16(),
        other => format!("// TODO(Phase 1.7 Block C FP8): wmma kernel for {:?}\n", other),
    }
}

const WMMA_FILE_HEADER: &str = r#"// Auto-generated by src_v1/ir/codegen_gpu.rs (Phase 1.7 Block A) —
// do not edit by hand. Textual v0.x template with a hardcoded dequant
// block per format; an IR-driven element-loop generator is Phase 2.

#include <hip/hip_runtime.h>
#include <hip/hip_fp16.h>
#include <stdint.h>
#include <cstring>

using half8  = _Float16 __attribute__((ext_vector_type(8)));
using float8 = float    __attribute__((ext_vector_type(8)));

// Kernel prolog — set MODE.FP_DENORM = 0xF (IEEE, preserves denormals)
// per dequant_ir_spec.md §7.4 Rule 4 / §10.5.
__device__ __forceinline__ void rf_v1_wmma_set_ieee_denormal_mode() {
    asm volatile("s_setreg_imm32_b32 hwreg(HW_REG_MODE, 4, 4), 0xF");
}

"#;

// Q4_0 FP16 WMMA kernel — 1:1 port of v0.x wmma_gemm_q4_0.hip with
// rf_v1_* symbol names and the IEEE-denormal prolog. Tile sizes:
// TILE_M=64, TILE_N=64, K_CHUNK=32, 128 threads (4 waves) per block.
fn emit_q4_0_wmma_fp16() -> String {
    let mut s = String::from(WMMA_FILE_HEADER);
    s.push_str(r#"// Q4_0 FP16 WMMA GEMM — D[M×N] = A[M×K] * W[N×K] with W in Q4_0.
// Layout copied verbatim from hip_kernels/wmma/wmma_gemm_q4_0.hip so
// gfx1201 A/B fragment offsets and LDS coalescing stay known-good.

#define TILE_M          64
#define TILE_N          64
#define TILE_K          16
#define K_CHUNK         32
#define WARPS_PER_BLOCK 4
#define THREADS_PER_BLOCK (WARPS_PER_BLOCK * 32)
#define COL_BLOCKS      4
#define Q4_0_BLOCK_BYTES 18

__global__ void rf_v1_wmma_gemm_q4_0_fp16_kernel(
    const float*   __restrict__ A,
    const uint8_t* __restrict__ W,
    float*         __restrict__ D,
    int M, int N, int K)
{
    rf_v1_wmma_set_ieee_denormal_mode();

    const int tile_m = blockIdx.y * TILE_M;
    const int tile_n = blockIdx.x * TILE_N;

    const int tid     = threadIdx.x;
    const int wave_id = tid >> 5;
    const int lane    = tid & 31;

    __shared__ __half lds_a[TILE_M * K_CHUNK];
    __shared__ __half lds_b[K_CHUNK * TILE_N];

    float8 acc[COL_BLOCKS];
    #pragma unroll
    for (int b = 0; b < COL_BLOCKS; ++b) {
        acc[b] = {0, 0, 0, 0, 0, 0, 0, 0};
    }

    const int a_row_in_tile = wave_id * 16 + (lane & 15);
    const int a_k_set       = (lane >> 4) * 4;
    const int col_in_lane   = lane & 15;
    const int b_k_set       = (lane >> 4) * 4;

    const int blocks_per_row = K / 32;
    const int num_k_chunks   = K / K_CHUNK;

    for (int kc = 0; kc < num_k_chunks; ++kc) {
        const int k_start_abs = kc * K_CHUNK;

        // A tile: global -> LDS, FP32 -> FP16 on the fly.
        #pragma unroll
        for (int i = 0; i < 16; ++i) {
            const int flat        = tid * 16 + i;
            const int row_in_tile = flat / K_CHUNK;
            const int k_in_tile   = flat & (K_CHUNK - 1);
            const float v = A[(tile_m + row_in_tile) * K + k_start_abs + k_in_tile];
            lds_a[flat] = __float2half(v);
        }

        // ===== Dequant block (Q4_0) — Phase-1 inline, IR-driven in Phase 2 =====
        {
            const int col  = tid >> 1;
            const int half = tid & 1;

            const size_t block_ofs =
                (size_t)(tile_n + col) * (size_t)blocks_per_row * Q4_0_BLOCK_BYTES +
                (size_t)kc * Q4_0_BLOCK_BYTES;
            const uint8_t* block_ptr = W + block_ofs;

            __half scale_h;
            std::memcpy(&scale_h, block_ptr, sizeof(__half));
            const float scale_f = __half2float(scale_h);

            const int qs_ofs = 2 + half * 8;
            uint8_t my_qs[8];
            #pragma unroll
            for (int i = 0; i < 8; ++i) my_qs[i] = block_ptr[qs_ofs + i];

            #pragma unroll
            for (int i = 0; i < 8; ++i) {
                const int k_lo = half * 8 + i;
                const int k_hi = k_lo + 16;
                const int nib_lo = int(my_qs[i] & 0x0F) - 8;
                const int nib_hi = int(my_qs[i] >> 4)   - 8;
                lds_b[k_lo * TILE_N + col] = __float2half(float(nib_lo) * scale_f);
                lds_b[k_hi * TILE_N + col] = __float2half(float(nib_hi) * scale_f);
            }
        }
        // ===================================================================

        __syncthreads();

        #pragma unroll
        for (int k_sub = 0; k_sub < K_CHUNK; k_sub += TILE_K) {
            half8 a_reg;
            {
                const int base = a_row_in_tile * K_CHUNK + k_sub;
                a_reg[0] = lds_a[base + a_k_set + 0];
                a_reg[1] = lds_a[base + a_k_set + 1];
                a_reg[2] = lds_a[base + a_k_set + 2];
                a_reg[3] = lds_a[base + a_k_set + 3];
                a_reg[4] = lds_a[base + a_k_set + 8];
                a_reg[5] = lds_a[base + a_k_set + 9];
                a_reg[6] = lds_a[base + a_k_set + 10];
                a_reg[7] = lds_a[base + a_k_set + 11];
            }

            #pragma unroll
            for (int cb = 0; cb < COL_BLOCKS; ++cb) {
                const int b_col_in_tile = cb * 16 + col_in_lane;

                half8 b_reg;
                b_reg[0] = lds_b[(k_sub + b_k_set + 0)  * TILE_N + b_col_in_tile];
                b_reg[1] = lds_b[(k_sub + b_k_set + 1)  * TILE_N + b_col_in_tile];
                b_reg[2] = lds_b[(k_sub + b_k_set + 2)  * TILE_N + b_col_in_tile];
                b_reg[3] = lds_b[(k_sub + b_k_set + 3)  * TILE_N + b_col_in_tile];
                b_reg[4] = lds_b[(k_sub + b_k_set + 8)  * TILE_N + b_col_in_tile];
                b_reg[5] = lds_b[(k_sub + b_k_set + 9)  * TILE_N + b_col_in_tile];
                b_reg[6] = lds_b[(k_sub + b_k_set + 10) * TILE_N + b_col_in_tile];
                b_reg[7] = lds_b[(k_sub + b_k_set + 11) * TILE_N + b_col_in_tile];

                acc[cb] = __builtin_amdgcn_wmma_f32_16x16x16_f16_w32_gfx12(
                    a_reg, b_reg, acc[cb]);
            }
        }

        __syncthreads();
    }

    const int out_col_in_lane  = lane & 15;
    const int out_row_start    = (lane >> 4) * 8;
    const int wave_row_in_tile = wave_id * 16;

    #pragma unroll
    for (int cb = 0; cb < COL_BLOCKS; ++cb) {
        const int out_col_in_tile = cb * 16 + out_col_in_lane;
        const int global_col      = tile_n + out_col_in_tile;

        #pragma unroll
        for (int v = 0; v < 8; ++v) {
            const int out_row_in_tile = wave_row_in_tile + out_row_start + v;
            const int global_row      = tile_m + out_row_in_tile;
            D[global_row * N + global_col] = acc[cb][v];
        }
    }
}

extern "C" hipError_t rocmforge_launch_wmma_gemm_q4_0_fp16(
    const float*   input,
    const uint8_t* weights,
    float*         output,
    int M, int N, int K,
    hipStream_t stream)
{
    if (M <= 0 || N <= 0 || K <= 0)   return hipErrorInvalidValue;
    if ((M % TILE_M)  != 0)           return hipErrorInvalidValue;
    if ((N % TILE_N)  != 0)           return hipErrorInvalidValue;
    if ((K % K_CHUNK) != 0)           return hipErrorInvalidValue;

    dim3 grid(N / TILE_N, M / TILE_M, 1);
    dim3 block(THREADS_PER_BLOCK, 1, 1);

    rf_v1_wmma_gemm_q4_0_fp16_kernel<<<grid, block, 0, stream>>>(
        input, weights, output, M, N, K);
    return hipGetLastError();
}
"#);
    s
}

/// Emit every Phase-1-supported WMMA kernel as a `(filename, source)`
/// list. The build system writes each entry to its own `.hip` file so
/// CMake can build them as independent static libraries.
pub fn emit_all_wmma_files() -> Vec<(&'static str, String)> {
    vec![
        ("wmma/wmma_gemm_q4_0_fp16.hip", emit_q4_0_wmma_fp16()),
        ("wmma/wmma_gemm_q4_k_fp16.hip", emit_q4_k_wmma_fp16()),
        ("wmma/wmma_gemm_q6_k_fp16.hip", emit_q6_k_wmma_fp16()),
        ("wmma/wmma_gemm_q8_0_fp16.hip", emit_q8_0_wmma_fp16()),
    ]
}

/// Concatenated view of all WMMA kernels, retained for inspection and
/// backwards-compatibility of the existing drift test. Use
/// [`emit_all_wmma_files`] when one file per kernel is needed.
pub fn emit_all_wmma_kernels() -> String {
    let mut s = String::new();
    for (_, src) in emit_all_wmma_files() {
        s.push_str(&src);
    }
    s
}

// Q4_K FP16 WMMA — 1:1 port of hip_kernels/wmma/wmma_gemm_q4_k.hip.
// Same tile geometry as Q4_0; only the dequant block differs. Pair-
// interleaved sub-block layout (sub_idx paired with sub_idx^1) and
// get_scale_min_k4 6-bit unpack without any /64.
fn emit_q4_k_wmma_fp16() -> String {
    let mut s = String::from(WMMA_FILE_HEADER);
    s.push_str(r#"// Q4_K FP16 WMMA GEMM — D[M×N] = A[M×K] * W[N×K] with W in Q4_K.
// Layout copied verbatim from hip_kernels/wmma/wmma_gemm_q4_k.hip.

#define TILE_M             64
#define TILE_N             64
#define TILE_K             16
#define K_CHUNK            32
#define WARPS_PER_BLOCK    4
#define THREADS_PER_BLOCK  (WARPS_PER_BLOCK * 32)
#define COL_BLOCKS         4
#define Q4_K_BLOCK_BYTES       144
#define Q4_K_ELEMS_PER_BLOCK   256

__global__ void rf_v1_wmma_gemm_q4_k_fp16_kernel(
    const float*   __restrict__ A,
    const uint8_t* __restrict__ W,
    float*         __restrict__ D,
    int M, int N, int K)
{
    rf_v1_wmma_set_ieee_denormal_mode();

    const int tile_m = blockIdx.y * TILE_M;
    const int tile_n = blockIdx.x * TILE_N;

    const int tid     = threadIdx.x;
    const int wave_id = tid >> 5;
    const int lane    = tid & 31;

    __shared__ __half lds_a[TILE_M * K_CHUNK];
    __shared__ __half lds_b[K_CHUNK * TILE_N];

    float8 acc[COL_BLOCKS];
    #pragma unroll
    for (int b = 0; b < COL_BLOCKS; ++b) {
        acc[b] = {0, 0, 0, 0, 0, 0, 0, 0};
    }

    const int a_row_in_tile = wave_id * 16 + (lane & 15);
    const int a_k_set       = (lane >> 4) * 4;
    const int col_in_lane   = lane & 15;
    const int b_k_set       = (lane >> 4) * 4;

    const int super_blocks_per_row = K / Q4_K_ELEMS_PER_BLOCK;
    const int num_k_chunks         = K / K_CHUNK;

    for (int kc = 0; kc < num_k_chunks; ++kc) {
        const int k_start_abs = kc * K_CHUNK;

        #pragma unroll
        for (int i = 0; i < 16; ++i) {
            const int flat        = tid * 16 + i;
            const int row_in_tile = flat / K_CHUNK;
            const int k_in_tile   = flat & (K_CHUNK - 1);
            const float v = A[(tile_m + row_in_tile) * K + k_start_abs + k_in_tile];
            lds_a[flat] = __float2half(v);
        }

        // ===== Dequant block (Q4_K pair-interleaved) =====
        {
            const int col  = tid >> 1;
            const int half = tid & 1;

            const int super_block_idx = kc >> 3;
            const int sub_idx         = kc & 7;

            const size_t sb_ofs =
                (size_t)(tile_n + col) * (size_t)super_blocks_per_row * Q4_K_BLOCK_BYTES
                + (size_t)super_block_idx * Q4_K_BLOCK_BYTES;
            const uint8_t* sb_ptr = W + sb_ofs;

            __half d_h, dmin_h;
            std::memcpy(&d_h,    sb_ptr + 0, sizeof(__half));
            std::memcpy(&dmin_h, sb_ptr + 2, sizeof(__half));
            const float d_f    = __half2float(d_h);
            const float dmin_f = __half2float(dmin_h);

            const uint8_t* scales = sb_ptr + 4;
            int scale_j, min_j;
            if (sub_idx < 4) {
                scale_j = scales[sub_idx]     & 0x3F;
                min_j   = scales[sub_idx + 4] & 0x3F;
            } else {
                scale_j = (scales[sub_idx + 4] & 0x0F) | ((scales[sub_idx - 4] >> 6) << 4);
                min_j   = (scales[sub_idx + 4] >> 4)   | ((scales[sub_idx]     >> 6) << 4);
            }
            const float d_scale = d_f    * (float)scale_j;
            const float d_mn    = dmin_f * (float)min_j;

            const int pair_base = (sub_idx >> 1) * 32;
            const bool is_upper = (sub_idx & 1) != 0;
            const uint8_t* qs_base = sb_ptr + 16 + pair_base + half * 16;

            #pragma unroll
            for (int i = 0; i < 16; ++i) {
                const uint8_t byte = qs_base[i];
                const int nib = is_upper ? (byte >> 4) : (byte & 0x0F);
                const int k   = half * 16 + i;
                lds_b[k * TILE_N + col] = __float2half(d_scale * (float)nib - d_mn);
            }
        }
        // ===================================================================

        __syncthreads();

        #pragma unroll
        for (int k_sub = 0; k_sub < K_CHUNK; k_sub += TILE_K) {
            half8 a_reg;
            {
                const int base = a_row_in_tile * K_CHUNK + k_sub;
                a_reg[0] = lds_a[base + a_k_set + 0];
                a_reg[1] = lds_a[base + a_k_set + 1];
                a_reg[2] = lds_a[base + a_k_set + 2];
                a_reg[3] = lds_a[base + a_k_set + 3];
                a_reg[4] = lds_a[base + a_k_set + 8];
                a_reg[5] = lds_a[base + a_k_set + 9];
                a_reg[6] = lds_a[base + a_k_set + 10];
                a_reg[7] = lds_a[base + a_k_set + 11];
            }

            #pragma unroll
            for (int cb = 0; cb < COL_BLOCKS; ++cb) {
                const int b_col_in_tile = cb * 16 + col_in_lane;

                half8 b_reg;
                b_reg[0] = lds_b[(k_sub + b_k_set + 0)  * TILE_N + b_col_in_tile];
                b_reg[1] = lds_b[(k_sub + b_k_set + 1)  * TILE_N + b_col_in_tile];
                b_reg[2] = lds_b[(k_sub + b_k_set + 2)  * TILE_N + b_col_in_tile];
                b_reg[3] = lds_b[(k_sub + b_k_set + 3)  * TILE_N + b_col_in_tile];
                b_reg[4] = lds_b[(k_sub + b_k_set + 8)  * TILE_N + b_col_in_tile];
                b_reg[5] = lds_b[(k_sub + b_k_set + 9)  * TILE_N + b_col_in_tile];
                b_reg[6] = lds_b[(k_sub + b_k_set + 10) * TILE_N + b_col_in_tile];
                b_reg[7] = lds_b[(k_sub + b_k_set + 11) * TILE_N + b_col_in_tile];

                acc[cb] = __builtin_amdgcn_wmma_f32_16x16x16_f16_w32_gfx12(
                    a_reg, b_reg, acc[cb]);
            }
        }

        __syncthreads();
    }

    const int out_col_in_lane  = lane & 15;
    const int out_row_start    = (lane >> 4) * 8;
    const int wave_row_in_tile = wave_id * 16;

    #pragma unroll
    for (int cb = 0; cb < COL_BLOCKS; ++cb) {
        const int out_col_in_tile = cb * 16 + out_col_in_lane;
        const int global_col      = tile_n + out_col_in_tile;

        #pragma unroll
        for (int v = 0; v < 8; ++v) {
            const int out_row_in_tile = wave_row_in_tile + out_row_start + v;
            const int global_row      = tile_m + out_row_in_tile;
            D[global_row * N + global_col] = acc[cb][v];
        }
    }
}

extern "C" hipError_t rocmforge_launch_wmma_gemm_q4_k_fp16(
    const float*   input,
    const uint8_t* weights,
    float*         output,
    int M, int N, int K,
    hipStream_t stream)
{
    if (M <= 0 || N <= 0 || K <= 0)                  return hipErrorInvalidValue;
    if ((M % TILE_M) != 0)                           return hipErrorInvalidValue;
    if ((N % TILE_N) != 0)                           return hipErrorInvalidValue;
    if ((K % Q4_K_ELEMS_PER_BLOCK) != 0)             return hipErrorInvalidValue;

    dim3 grid(N / TILE_N, M / TILE_M, 1);
    dim3 block(THREADS_PER_BLOCK, 1, 1);

    rf_v1_wmma_gemm_q4_k_fp16_kernel<<<grid, block, 0, stream>>>(
        input, weights, output, M, N, K);
    return hipGetLastError();
}
"#);
    s
}

// Q6_K FP16 WMMA — 1:1 port of hip_kernels/wmma/wmma_gemm_q6_k.hip.
// 210-byte super-block with d at offset 208, int8 scales @ 192, llama.cpp
// qh layout (4 elements per qh byte at strides of 32 within each half).
fn emit_q6_k_wmma_fp16() -> String {
    let mut s = String::from(WMMA_FILE_HEADER);
    s.push_str(r#"// Q6_K FP16 WMMA GEMM — D[M×N] = A[M×K] * W[N×K] with W in Q6_K.
// Layout copied verbatim from hip_kernels/wmma/wmma_gemm_q6_k.hip.

#define TILE_M             64
#define TILE_N             64
#define TILE_K             16
#define K_CHUNK            32
#define WARPS_PER_BLOCK    4
#define THREADS_PER_BLOCK  (WARPS_PER_BLOCK * 32)
#define COL_BLOCKS         4
#define Q6_K_BLOCK_BYTES       210
#define Q6_K_ELEMS_PER_BLOCK   256

__global__ void rf_v1_wmma_gemm_q6_k_fp16_kernel(
    const float*   __restrict__ A,
    const uint8_t* __restrict__ W,
    float*         __restrict__ D,
    int M, int N, int K)
{
    rf_v1_wmma_set_ieee_denormal_mode();

    const int tile_m = blockIdx.y * TILE_M;
    const int tile_n = blockIdx.x * TILE_N;

    const int tid     = threadIdx.x;
    const int wave_id = tid >> 5;
    const int lane    = tid & 31;

    __shared__ __half lds_a[TILE_M * K_CHUNK];
    __shared__ __half lds_b[K_CHUNK * TILE_N];

    float8 acc[COL_BLOCKS];
    #pragma unroll
    for (int b = 0; b < COL_BLOCKS; ++b) {
        acc[b] = {0, 0, 0, 0, 0, 0, 0, 0};
    }

    const int a_row_in_tile = wave_id * 16 + (lane & 15);
    const int a_k_set       = (lane >> 4) * 4;
    const int col_in_lane   = lane & 15;
    const int b_k_set       = (lane >> 4) * 4;

    const int super_blocks_per_row = K / Q6_K_ELEMS_PER_BLOCK;
    const int num_k_chunks         = K / K_CHUNK;

    for (int kc = 0; kc < num_k_chunks; ++kc) {
        const int k_start_abs = kc * K_CHUNK;

        #pragma unroll
        for (int i = 0; i < 16; ++i) {
            const int flat        = tid * 16 + i;
            const int row_in_tile = flat / K_CHUNK;
            const int k_in_tile   = flat & (K_CHUNK - 1);
            const float v = A[(tile_m + row_in_tile) * K + k_start_abs + k_in_tile];
            lds_a[flat] = __float2half(v);
        }

        // ===== Dequant block (Q6_K llama.cpp layout) =====
        {
            const int col  = tid >> 1;
            const int half = tid & 1;

            const int super_block_idx = kc >> 3;
            const int chunk_in_sb     = kc & 7;

            const size_t sb_ofs =
                (size_t)(tile_n + col) * (size_t)super_blocks_per_row * Q6_K_BLOCK_BYTES
                + (size_t)super_block_idx * Q6_K_BLOCK_BYTES;
            const uint8_t* sb_ptr = W + sb_ofs;

            __half d_h;
            std::memcpy(&d_h, sb_ptr + 208, sizeof(__half));
            const float d_f = __half2float(d_h);

            const int chunk_base = chunk_in_sb * 32 + half * 16;
            const int sub_idx    = chunk_base >> 4;
            const int n_half     = chunk_base >> 7;
            const int e_half     = chunk_base & 127;
            const int which_q    = e_half >> 5;
            const int l_base     = e_half & 31;
            const bool is_high_nib = (which_q >= 2);
            const int qh_shift   = 2 * which_q;

            const int8_t* scales = reinterpret_cast<const int8_t*>(sb_ptr + 192);
            const float d_scale = d_f * (float)scales[sub_idx];

            const uint8_t* ql_base = sb_ptr
                + (size_t)n_half * 64
                + (size_t)((which_q & 1) * 32)
                + (size_t)l_base;
            const uint8_t* qh_base = sb_ptr
                + 128
                + (size_t)n_half * 32
                + (size_t)l_base;

            #pragma unroll
            for (int i = 0; i < 16; ++i) {
                const uint8_t ql_byte = ql_base[i];
                const uint8_t qh_byte = qh_base[i];
                const int ql_nib  = is_high_nib ? (ql_byte >> 4) : (ql_byte & 0x0F);
                const int qh_bits = (qh_byte >> qh_shift) & 0x3;
                const int q6 = ql_nib | (qh_bits << 4);
                const int signed_q = q6 - 32;
                const int k = half * 16 + i;
                lds_b[k * TILE_N + col] = __float2half(d_scale * (float)signed_q);
            }
        }
        // ===================================================================

        __syncthreads();

        #pragma unroll
        for (int k_sub = 0; k_sub < K_CHUNK; k_sub += TILE_K) {
            half8 a_reg;
            {
                const int base = a_row_in_tile * K_CHUNK + k_sub;
                a_reg[0] = lds_a[base + a_k_set + 0];
                a_reg[1] = lds_a[base + a_k_set + 1];
                a_reg[2] = lds_a[base + a_k_set + 2];
                a_reg[3] = lds_a[base + a_k_set + 3];
                a_reg[4] = lds_a[base + a_k_set + 8];
                a_reg[5] = lds_a[base + a_k_set + 9];
                a_reg[6] = lds_a[base + a_k_set + 10];
                a_reg[7] = lds_a[base + a_k_set + 11];
            }

            #pragma unroll
            for (int cb = 0; cb < COL_BLOCKS; ++cb) {
                const int b_col_in_tile = cb * 16 + col_in_lane;

                half8 b_reg;
                b_reg[0] = lds_b[(k_sub + b_k_set + 0)  * TILE_N + b_col_in_tile];
                b_reg[1] = lds_b[(k_sub + b_k_set + 1)  * TILE_N + b_col_in_tile];
                b_reg[2] = lds_b[(k_sub + b_k_set + 2)  * TILE_N + b_col_in_tile];
                b_reg[3] = lds_b[(k_sub + b_k_set + 3)  * TILE_N + b_col_in_tile];
                b_reg[4] = lds_b[(k_sub + b_k_set + 8)  * TILE_N + b_col_in_tile];
                b_reg[5] = lds_b[(k_sub + b_k_set + 9)  * TILE_N + b_col_in_tile];
                b_reg[6] = lds_b[(k_sub + b_k_set + 10) * TILE_N + b_col_in_tile];
                b_reg[7] = lds_b[(k_sub + b_k_set + 11) * TILE_N + b_col_in_tile];

                acc[cb] = __builtin_amdgcn_wmma_f32_16x16x16_f16_w32_gfx12(
                    a_reg, b_reg, acc[cb]);
            }
        }

        __syncthreads();
    }

    const int out_col_in_lane  = lane & 15;
    const int out_row_start    = (lane >> 4) * 8;
    const int wave_row_in_tile = wave_id * 16;

    #pragma unroll
    for (int cb = 0; cb < COL_BLOCKS; ++cb) {
        const int out_col_in_tile = cb * 16 + out_col_in_lane;
        const int global_col      = tile_n + out_col_in_tile;

        #pragma unroll
        for (int v = 0; v < 8; ++v) {
            const int out_row_in_tile = wave_row_in_tile + out_row_start + v;
            const int global_row      = tile_m + out_row_in_tile;
            D[global_row * N + global_col] = acc[cb][v];
        }
    }
}

extern "C" hipError_t rocmforge_launch_wmma_gemm_q6_k_fp16(
    const float*   input,
    const uint8_t* weights,
    float*         output,
    int M, int N, int K,
    hipStream_t stream)
{
    if (M <= 0 || N <= 0 || K <= 0)                  return hipErrorInvalidValue;
    if ((M % TILE_M) != 0)                           return hipErrorInvalidValue;
    if ((N % TILE_N) != 0)                           return hipErrorInvalidValue;
    if ((K % Q6_K_ELEMS_PER_BLOCK) != 0)             return hipErrorInvalidValue;

    dim3 grid(N / TILE_N, M / TILE_M, 1);
    dim3 block(THREADS_PER_BLOCK, 1, 1);

    rf_v1_wmma_gemm_q6_k_fp16_kernel<<<grid, block, 0, stream>>>(
        input, weights, output, M, N, K);
    return hipGetLastError();
}
"#);
    s
}

// Q8_0 FP16 WMMA — v0.x has no Q8_0 weight WMMA (Q8_0 is only used for
// activations in the Q8-Inline GEMV path). New kernel using the Q4_0
// tile geometry; dequant is trivial (signed int8 × FP16 scale).
fn emit_q8_0_wmma_fp16() -> String {
    let mut s = String::from(WMMA_FILE_HEADER);
    s.push_str(r#"// Q8_0 FP16 WMMA GEMM — D[M×N] = A[M×K] * W[N×K] with W in Q8_0.
// No v0.x reference; tile geometry follows Q4_0. Q8_0 block is 34 B for
// 32 elements: FP16 d @ 0, signed int8 qs[32] @ 2.

#define TILE_M             64
#define TILE_N             64
#define TILE_K             16
#define K_CHUNK            32
#define WARPS_PER_BLOCK    4
#define THREADS_PER_BLOCK  (WARPS_PER_BLOCK * 32)
#define COL_BLOCKS         4
#define Q8_0_BLOCK_BYTES   34

__global__ void rf_v1_wmma_gemm_q8_0_fp16_kernel(
    const float*   __restrict__ A,
    const uint8_t* __restrict__ W,
    float*         __restrict__ D,
    int M, int N, int K)
{
    rf_v1_wmma_set_ieee_denormal_mode();

    const int tile_m = blockIdx.y * TILE_M;
    const int tile_n = blockIdx.x * TILE_N;

    const int tid     = threadIdx.x;
    const int wave_id = tid >> 5;
    const int lane    = tid & 31;

    __shared__ __half lds_a[TILE_M * K_CHUNK];
    __shared__ __half lds_b[K_CHUNK * TILE_N];

    float8 acc[COL_BLOCKS];
    #pragma unroll
    for (int b = 0; b < COL_BLOCKS; ++b) {
        acc[b] = {0, 0, 0, 0, 0, 0, 0, 0};
    }

    const int a_row_in_tile = wave_id * 16 + (lane & 15);
    const int a_k_set       = (lane >> 4) * 4;
    const int col_in_lane   = lane & 15;
    const int b_k_set       = (lane >> 4) * 4;

    const int blocks_per_row = K / 32;
    const int num_k_chunks   = K / K_CHUNK;

    for (int kc = 0; kc < num_k_chunks; ++kc) {
        const int k_start_abs = kc * K_CHUNK;

        #pragma unroll
        for (int i = 0; i < 16; ++i) {
            const int flat        = tid * 16 + i;
            const int row_in_tile = flat / K_CHUNK;
            const int k_in_tile   = flat & (K_CHUNK - 1);
            const float v = A[(tile_m + row_in_tile) * K + k_start_abs + k_in_tile];
            lds_a[flat] = __float2half(v);
        }

        // ===== Dequant block (Q8_0 — signed int8) =====
        {
            const int col  = tid >> 1;
            const int half = tid & 1;

            const size_t block_ofs =
                (size_t)(tile_n + col) * (size_t)blocks_per_row * Q8_0_BLOCK_BYTES +
                (size_t)kc * Q8_0_BLOCK_BYTES;
            const uint8_t* block_ptr = W + block_ofs;

            __half scale_h;
            std::memcpy(&scale_h, block_ptr, sizeof(__half));
            const float scale_f = __half2float(scale_h);

            const int qs_ofs = 2 + half * 16;
            #pragma unroll
            for (int i = 0; i < 16; ++i) {
                const int8_t q8 = (int8_t)block_ptr[qs_ofs + i];
                const int k = half * 16 + i;
                lds_b[k * TILE_N + col] = __float2half((float)q8 * scale_f);
            }
        }
        // ===================================================================

        __syncthreads();

        #pragma unroll
        for (int k_sub = 0; k_sub < K_CHUNK; k_sub += TILE_K) {
            half8 a_reg;
            {
                const int base = a_row_in_tile * K_CHUNK + k_sub;
                a_reg[0] = lds_a[base + a_k_set + 0];
                a_reg[1] = lds_a[base + a_k_set + 1];
                a_reg[2] = lds_a[base + a_k_set + 2];
                a_reg[3] = lds_a[base + a_k_set + 3];
                a_reg[4] = lds_a[base + a_k_set + 8];
                a_reg[5] = lds_a[base + a_k_set + 9];
                a_reg[6] = lds_a[base + a_k_set + 10];
                a_reg[7] = lds_a[base + a_k_set + 11];
            }

            #pragma unroll
            for (int cb = 0; cb < COL_BLOCKS; ++cb) {
                const int b_col_in_tile = cb * 16 + col_in_lane;

                half8 b_reg;
                b_reg[0] = lds_b[(k_sub + b_k_set + 0)  * TILE_N + b_col_in_tile];
                b_reg[1] = lds_b[(k_sub + b_k_set + 1)  * TILE_N + b_col_in_tile];
                b_reg[2] = lds_b[(k_sub + b_k_set + 2)  * TILE_N + b_col_in_tile];
                b_reg[3] = lds_b[(k_sub + b_k_set + 3)  * TILE_N + b_col_in_tile];
                b_reg[4] = lds_b[(k_sub + b_k_set + 8)  * TILE_N + b_col_in_tile];
                b_reg[5] = lds_b[(k_sub + b_k_set + 9)  * TILE_N + b_col_in_tile];
                b_reg[6] = lds_b[(k_sub + b_k_set + 10) * TILE_N + b_col_in_tile];
                b_reg[7] = lds_b[(k_sub + b_k_set + 11) * TILE_N + b_col_in_tile];

                acc[cb] = __builtin_amdgcn_wmma_f32_16x16x16_f16_w32_gfx12(
                    a_reg, b_reg, acc[cb]);
            }
        }

        __syncthreads();
    }

    const int out_col_in_lane  = lane & 15;
    const int out_row_start    = (lane >> 4) * 8;
    const int wave_row_in_tile = wave_id * 16;

    #pragma unroll
    for (int cb = 0; cb < COL_BLOCKS; ++cb) {
        const int out_col_in_tile = cb * 16 + out_col_in_lane;
        const int global_col      = tile_n + out_col_in_tile;

        #pragma unroll
        for (int v = 0; v < 8; ++v) {
            const int out_row_in_tile = wave_row_in_tile + out_row_start + v;
            const int global_row      = tile_m + out_row_in_tile;
            D[global_row * N + global_col] = acc[cb][v];
        }
    }
}

extern "C" hipError_t rocmforge_launch_wmma_gemm_q8_0_fp16(
    const float*   input,
    const uint8_t* weights,
    float*         output,
    int M, int N, int K,
    hipStream_t stream)
{
    if (M <= 0 || N <= 0 || K <= 0)   return hipErrorInvalidValue;
    if ((M % TILE_M)  != 0)           return hipErrorInvalidValue;
    if ((N % TILE_N)  != 0)           return hipErrorInvalidValue;
    if ((K % K_CHUNK) != 0)           return hipErrorInvalidValue;

    dim3 grid(N / TILE_N, M / TILE_M, 1);
    dim3 block(THREADS_PER_BLOCK, 1, 1);

    rf_v1_wmma_gemm_q8_0_fp16_kernel<<<grid, block, 0, stream>>>(
        input, weights, output, M, N, K);
    return hipGetLastError();
}
"#);
    s
}
